### ISSUE TITLE
Yii version?

### ISSUE THREAD

**Issue by mckracken83** [markokeeffe/yii-assets#1]
Is this for Yii2 or Yii 1.1? I'm on 1.1 and I'm trying to install it, and I'm hitting some snags. Extracted it to my extensions directory, entered info into my config (had to change the class paths) and got a strange error about $Assets being undefined? Would love to use the extension - been having a hard time finding something that minifies but for CDN delivery.

**Comment by markokeeffe** [comment]
This is for Yii1.1 but uses composer autoload. You may find this useful: http://www.yiiframework.com/doc/guide/1.1/en/extension.integration#using-3rd-party-autoloaders
